### ISSUE TITLE
`files.copy`

### ISSUE THREAD

**Issue by yellowhat** [Fizzadar/pyinfra#1121]
## Is your feature request related to a problem? Please describe

Hi,
I would like to copy a file on another path on the targets.

Ansible provides `ansible.builtin.copy` for this kind of operation:

```yaml
    - name: Kubernetes - .kube/config (user)
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "~{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
        remote_src: true
```

But I cannot find an equivalent one in `pyinfra`.

I have to run a `shell` command:
 
```python
    server.shell(
        name=f"Kubeconfig - .kube/config ({host.data.ssh_user})",
        commands=[
            "cp /etc/rancher/k3s/k3s.yaml .kube/config",
            f"chown {host.data.ssh_user}:{host.data.ssh_user} .kube/config",
        ]
    )
```

## Describe the solution you'd like

Add `files.copy` to copy files on the target itself.

Thanks
